### ISSUE TITLE
Adding a new Kotlin folder and also adding my project in it 

### ISSUE THREAD

**Issue by Yashsomalkar** [InvisiblePro/Hacktoberfest-2022#133]
My project is a native android application SAVY. Which can be very useful in saving vital email addresses.

I request you to go through my project and merge it in your repo 😄. 

mentions: @InvisiblePro

**Comment by Yashsomalkar** [comment]
I have added my project and also the new folder 📂. Looking forward to see my contribution in your repo 🧑‍💻. 
@InvisiblePro

**Comment by InvisiblePro** [comment]
Yea, Nice work dude!
